# Makefile for lab7

COMPILER_TYPE= gnu

CC= gcc

PROG= lab7
SRCS= lab7.c test7.c UART.c

CCFLAGS= -Wall

DPADD+= ${LIBDRIVER} ${LIBSYS}
LDADD+= -ldriver -lsys

LDFLAGS+= -L .

MAN=

.include <bsd.prog.mk>
.include <bsd.gcc.mk>
